"use client";

import { motion } from "framer-motion";
import { ArrowLeft, CalendarDays, CheckCircle2, MessageCircle } from "lucide-react";
import Link from "next/link";
import type { CSSProperties } from "react";
import { useParams } from "next/navigation";

const C = { bg: "#170000", wine: "#5b0707", red: "#a10f12", gold: "#d8a33f", gold2: "#ffd878", cream: "#fff4df", text: "#fff7e8", muted: "#e7cda3", dark: "#260000" };
const whatsapp = "https://wa.me/5521974796718?text=Olá! Vim pelo site e gostaria de uma proposta.";

const data: Record<string, { title: string; label: string; duration: string; description: string; topics: string[]; benefits: string[] }> = {
  "impulso-essencial": { title: "Impulso Essencial", label: "Pacote", duration: "1 dia", description: "Treinamento básico de primeiros socorros para empresas que desejam prevenir, agir com segurança e salvar vidas.", topics: ["Avaliação inicial da vítima", "Acionamento correto do socorro", "Engasgo", "RCP", "DEA", "Desmaios", "Quedas", "Queimaduras"], benefits: ["Prevenção de acidentes", "Equipe preparada", "Conformidade", "Cuidado que gera valor"] },
  "impulso-cuidar": { title: "Impulso Cuidar", label: "Plano", duration: "1 dia", description: "Primeiros socorros e monitorização básica para atuar com segurança nas principais emergências do dia a dia.", topics: ["RCP", "Engasgo", "Pressão arterial", "Oximetria", "Temperatura corporal", "Frequência cardíaca", "Glicemia", "Sinais de alerta"], benefits: ["Prevenção", "Produtividade", "Cuidado", "Segurança"] },
  "impulso-experience": { title: "Impulso Experience", label: "Pacote", duration: "2 dias", description: "Experiência prática completa, intensiva, dinâmica e com simulações realistas para equipes corporativas.", topics: ["Dia 1: conteúdo teórico", "Dia 2: prática e simulações", "Cenários de emergência", "Casos práticos", "Dinâmicas", "Instrutores especializados"], benefits: ["Equipe confiante", "Ambiente seguro", "Resultado prático", "Cultura de prevenção"] },
  "lei-lucas": { title: "Lei Lucas", label: "Plano", duration: "2h a 8h", description: "Capacitação obrigatória conforme Lei nº 13.722/2018 para escolas e espaços recreativos infantis.", topics: ["Engasgo em bebês", "RCP pediátrica", "Desmaios", "Convulsão", "Quedas", "Queimaduras", "Crises alérgicas", "Febre"], benefits: ["Mais segurança", "Cumprimento da lei", "Confiança dos pais", "Valorização da instituição"] },
  "saude-da-mulher": { title: "Saúde da Mulher", label: "Palestra", duration: "60 a 90 minutos", description: "Palestra sobre saúde, autocuidado, prevenção e valorização da mulher no ambiente corporativo.", topics: ["Saúde física", "Saúde emocional", "Ciclo menstrual", "Climatério", "Hábitos saudáveis", "Sono", "Estresse", "Acolhimento"], benefits: ["Engajamento", "Redução de afastamentos", "Clima organizacional", "Retenção de talentos"] },
  "saude-seguranca-masculina": { title: "Saúde e Segurança Masculina", label: "Palestra", duration: "60 a 90 minutos", description: "Conscientização sobre prevenção, segurança, saúde masculina e responsabilidade no ambiente de trabalho.", topics: ["Infarto", "Pressão alta", "Cansaço extremo", "Estresse", "Burnout", "Acidentes", "Primeiros cuidados", "Autocuidado"], benefits: ["Redução de acidentes", "Funcionários saudáveis", "Mais segurança", "Cultura de cuidado"] },
  "saude-mental": { title: "Saúde Mental Corporativa", label: "Conteúdo", duration: "Personalizado", description: "Informação correta, acolhimento e cultura de cuidado para ambientes emocionalmente mais saudáveis.", topics: ["Mitos e verdades", "Escuta", "Acolhimento", "Prevenção", "Bem-estar", "Rotina", "Tratamento", "Cultura de cuidado"], benefits: ["Ambiente saudável", "Equipe acolhida", "Prevenção", "Humanização"] },
  "saude-e-seguranca": { title: "Saúde e Segurança", label: "Corporativo", duration: "1 dia", description: "Saúde ocupacional e bem-estar corporativo para empresas que valorizam pessoas e prevenção.", topics: ["Saúde mental", "NR-1", "Riscos psicossociais", "Ergonomia", "Esgotamento", "Saúde da mulher", "Cultura de cuidado", "Prevenção"], benefits: ["Prevenção", "Segurança", "Cultura de cuidado", "Resultados"] },
};

export default function TrainingPage() {
  const params = useParams<{ slug: string }>();
  const item = data[params.slug] || data["impulso-cuidar"];
  return <main style={s.page}><style>{`*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif}a{transition:.25s}a:hover{filter:brightness(1.08);transform:translateY(-2px)}@media(max-width:850px){.grid{grid-template-columns:1fr!important}.title{font-size:48px!important}.section{padding:35px 20px!important}}`}</style><section className="section" style={s.hero}><Link href="/" style={s.back}><ArrowLeft size={18} /> Voltar</Link><motion.div initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{duration:.7}}><span style={s.label}>{item.label}</span><h1 className="title" style={s.title}>{item.title}</h1><p style={s.desc}>{item.description}</p><div style={s.duration}><CalendarDays /> Formato: {item.duration}</div><a href={whatsapp} target="_blank" style={s.btn}><MessageCircle /> Solicitar orçamento</a></motion.div></section><section className="grid section" style={s.grid}><div style={s.card}><h2>Conteúdo abordado</h2>{item.topics.map(t=><p key={t} style={s.line}><CheckCircle2 size={18}/>{t}</p>)}</div><div style={s.card}><h2>Benefícios</h2>{item.benefits.map(t=><p key={t} style={s.line}><CheckCircle2 size={18}/>{t}</p>)}</div></section></main>;
}
const s: Record<string, CSSProperties> = { page:{minHeight:"100vh",background:`radial-gradient(circle at top left,${C.wine},${C.bg})`,color:C.text}, hero:{padding:"120px 7% 60px"}, back:{display:"inline-flex",alignItems:"center",gap:8,color:C.gold2,textDecoration:"none",marginBottom:30}, label:{display:"inline-block",padding:"10px 16px",borderRadius:999,background:C.gold,color:C.dark,fontWeight:900,textTransform:"uppercase"}, title:{fontSize:86,lineHeight:.95,margin:"22px 0",textTransform:"uppercase",letterSpacing:-3}, desc:{fontSize:22,lineHeight:1.7,color:C.muted,maxWidth:900},duration:{display:"inline-flex",alignItems:"center",gap:10,color:C.gold2,fontWeight:900,margin:"20px 0"},btn:{display:"flex",alignItems:"center",justifyContent:"center",gap:10,width:"fit-content",padding:"16px 26px",borderRadius:999,background:`linear-gradient(135deg,${C.gold},${C.gold2})`,color:C.dark,textDecoration:"none",fontWeight:1000,marginTop:20},grid:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:24,padding:"40px 7% 100px"},card:{padding:34,borderRadius:32,background:C.cream,color:C.dark},line:{display:"flex",alignItems:"center",gap:10,fontWeight:700}};
