"use client";
import { FormEvent, useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import { Mail, MessageCircle, Phone } from "lucide-react";
import { C, whatsappLink, instagramLink } from "@/data/siteData";
import SectionHeader from "./SectionHeader";
export default function Contact() { const [status, setStatus] = useState(""); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setStatus("Enviando..."); const form = new FormData(e.currentTarget); const payload = Object.fromEntries(form.entries()); const res = await fetch("/api/contato", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setStatus(res.ok ? "Mensagem enviada com sucesso!" : "Não foi possível enviar. Tente pelo WhatsApp."); if (res.ok) e.currentTarget.reset(); }
return <section id="contato" className="sectionPad" style={{ padding: "96px 7%" }}><SectionHeader tag="Contato" title="Solicite uma proposta personalizada." centered/><div className="contactGrid" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 26 }}><form onSubmit={submit} style={{ padding: 28, borderRadius: 30, background: C.cream, color: C.dark, display: "grid", gap: 14 }}><Input name="nome" placeholder="Nome"/><Input name="empresa" placeholder="Empresa"/><Input name="telefone" placeholder="Telefone/WhatsApp"/><Input name="email" placeholder="E-mail"/><select name="treinamento" style={input}><option>Selecione o treinamento</option><option>Impulso Essencial</option><option>Impulso Cuidar</option><option>Impulso Experience</option><option>Lei Lucas</option><option>Saúde Mental</option><option>Saúde da Mulher</option><option>Saúde e Segurança</option></select><textarea name="mensagem" placeholder="Mensagem" rows={5} style={{ ...input, resize: "vertical" }}/><button style={{ border: 0, cursor: "pointer", padding: 16, borderRadius: 999, background: `linear-gradient(135deg, ${C.gold}, ${C.gold2})`, color: C.dark, fontWeight: 900 }}>Enviar solicitação</button>{status && <strong>{status}</strong>}</form><div style={{ display: "grid", gap: 16 }}><ContactCard icon={<MessageCircle/>} title="WhatsApp" text="21 97479-6718" href={whatsappLink}/><ContactCard icon={<Phone/>} title="Instagram" text="@contato.impulsotreinamentos" href={instagramLink}/><ContactCard icon={<Mail/>} title="E-mail" text="informacoes@impulsotreinamentos.com.br" href="mailto:informacoes@impulsotreinamentos.com.br"/></div></div></section>; }
function Input(props: { name: string; placeholder: string }) { return <input {...props} required style={input}/>; }
function ContactCard({ icon, title, text, href }: { icon: ReactNode; title: string; text: string; href: string }) { return <a href={href} target="_blank" style={{ display: "flex", alignItems: "center", gap: 18, padding: 24, borderRadius: 28, background: "rgba(255,244,223,.08)", border: "1px solid rgba(255,216,120,.18)", color: C.cream }}><div style={{ color: C.gold2 }}>{icon}</div><div><strong style={{ display: "block" }}>{title}</strong><span style={{ color: C.muted }}>{text}</span></div></a>; }
const input: CSSProperties = { width: "100%", padding: "15px 16px", borderRadius: 16, border: "1px solid rgba(91,7,7,.18)", outline: "none", fontSize: 15, background: "#fff", color: "#260000" };
