"use client";
import Image from "next/image";
import { motion, useScroll, useTransform } from "framer-motion";
import type { ReactNode } from "react";
import { CalendarDays, ChevronRight, GraduationCap, MessageCircle, Sparkles } from "lucide-react";
import { C, whatsappLink } from "@/data/siteData";
import Reveal from "./Reveal";
export default function Hero() {
  const { scrollYProgress } = useScroll();
  const yHero = useTransform(scrollYProgress, [0, .35], [0, -130]);
  const opacityHero = useTransform(scrollYProgress, [0, .3], [1, .5]);
  return <section id="inicio" className="heroGrid" style={{ minHeight: "88vh", display: "grid", gridTemplateColumns: "1.08fr .92fr", gap: 42, alignItems: "center", padding: "82px 7% 96px", position: "relative", overflow: "hidden" }}>
    <div style={{ position: "absolute", width: 360, height: 360, borderRadius: "50%", background: "rgba(255,216,120,.12)", filter: "blur(60px)", top: 40, left: -100 }} /><div style={{ position: "absolute", width: 420, height: 420, borderRadius: "50%", background: "rgba(161,15,18,.22)", filter: "blur(70px)", right: -120, bottom: 30 }} />
    <motion.div style={{ position: "relative", zIndex: 2, y: yHero, opacity: opacityHero }}><Reveal><div style={{ display: "inline-flex", alignItems: "center", gap: 9, padding: "10px 16px", borderRadius: 999, background: "rgba(255,244,223,.08)", border: "1px solid rgba(255,216,120,.3)", color: C.gold2, fontWeight: 900 }}><Sparkles size={17}/> Treinamentos corporativos em saúde e segurança</div></Reveal><Reveal delay={.1}><h1 className="heroTitle" style={{ margin: "22px 0 0", fontSize: "clamp(48px,7vw,92px)", lineHeight: .94, letterSpacing: -3, textTransform: "uppercase", color: C.text }}>Conhecimento que prepara. <span style={{ color: C.gold2 }}>Atitude que salva.</span></h1></Reveal><Reveal delay={.2}><p style={{ color: C.muted, fontSize: 20, lineHeight: 1.75, maxWidth: 760 }}>Capacitações práticas, humanizadas e atualizadas para empresas, escolas e equipes que desejam agir com confiança em situações reais.</p></Reveal><Reveal delay={.3}><div className="heroButtons" style={{ display: "flex", gap: 16, flexWrap: "wrap", marginTop: 32 }}><a href={whatsappLink} target="_blank" style={{ display: "inline-flex", alignItems: "center", gap: 10, padding: "16px 24px", borderRadius: 999, background: `linear-gradient(135deg, ${C.gold}, ${C.gold2})`, color: C.dark, fontWeight: 900, boxShadow: "0 18px 60px rgba(216,163,63,.3)" }}><MessageCircle size={20}/> Solicitar proposta</a><a href="#treinamentos" style={{ display: "inline-flex", alignItems: "center", gap: 8, padding: "16px 24px", borderRadius: 999, border: "1px solid rgba(255,216,120,.25)", color: C.cream, fontWeight: 900 }}>Conhecer treinamentos <ChevronRight size={18}/></a></div></Reveal></motion.div>
    <motion.div initial={{ opacity: 0, scale: .9, rotate: -3 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ duration: 1.1, ease: "easeOut" }} style={{ position: "relative", zIndex: 2, minHeight: 520, borderRadius: 38, padding: 34, background: "linear-gradient(145deg, rgba(255,244,223,.13), rgba(255,255,255,.04))", border: "1px solid rgba(255,216,120,.32)", boxShadow: "0 34px 120px rgba(0,0,0,.42)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", textAlign: "center", animation: "floatPulse 7s ease-in-out infinite" }}>
      <div style={{ width: 190, height: 190, borderRadius: 42, overflow: "hidden", background: C.cream, display: "grid", placeItems: "center", border: `2px solid ${C.gold}`, boxShadow: "0 0 90px rgba(216,163,63,.35)" }}><Image src="/logo.png" alt="Logo Impulso Treinamentos" width={190} height={190} style={{ objectFit: "contain", width: "100%", height: "100%" }}/></div><h2 style={{ fontSize: 34, margin: "26px 0 8px", textTransform: "uppercase", letterSpacing: 1 }}>Impulso Treinamentos</h2><p style={{ color: C.muted, fontSize: 17 }}>Primeiros Socorros • Lei Lucas • Saúde Ocupacional • Bem-estar</p><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, width: "100%", marginTop: 24 }}><Mini icon={<CalendarDays/>} title="Formatos" text="1 ou 2 dias"/><Mini icon={<GraduationCap/>} title="Inclui" text="Certificado"/></div>
    </motion.div>
  </section>;
}
function Mini({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div style={{ padding: 16, borderRadius: 22, background: "rgba(255,244,223,.08)", border: "1px solid rgba(255,216,120,.18)", color: C.cream }}>{icon}<strong style={{ display: "block", marginTop: 8 }}>{title}</strong><span style={{ color: C.muted, fontSize: 13 }}>{text}</span></div>; }
